name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-jobs:
    name: Find Jobs
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.glob.outputs.paths }} 
    steps:
      - uses: actions/checkout@v4

      - name: Glob match
        uses: tj-actions/glob@v22
        id: glob
        with:
          files: |
            */Dockerfile

  matrix:
    name: Matrix Jobs
    needs: [find-jobs]
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders) }} 
    steps:
      - name: do something
        run: echo ${{ matrix.folder }}
