name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  search_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Search for outer directories
      id: search_directories
      uses: advanced-security/glob-match@v2
      with:
        pattern: '*/'
        flags: 'd'

    - name: Display directories
      run: echo "Directories found:" ${{ steps.search_directories.outputs.files }}
