name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  search_directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository contents
        id: directory
        run: |
          echo "directories=$(ls -d */ | grep -Ev '^(thor|dev_)' | tr -d '\n\r' | sed 's@/$@@g')" >> $GITHUB_OUTPUT

      - name: Iterate over directories
        run: |
          IFS='/' read -ra dirs <<< "${{ steps.directory.outputs.directories }}"
          for dir in "${dirs[@]}"; do
            echo "Processing directory: $dir"
          done
