name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  search_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Glob match
      id: search_directories
      uses: tj-actions/glob@v22
      with:
        files: '**'

    - name: Display directories
      run: echo "Directories found:" ${{ steps.search_directories.outputs.files }}
