name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  search_directories:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.directory.outputs.directories }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository contents
        id: directory
        run: |
          directories=$(ls -d */ | grep -Ev '^(thor|dev_)' | tr -d '\n\r' | sed 's@/$@@g')
          echo "directories=[\"$directories\"]" >> $GITHUB_OUTPUT 

  test_listing: # New job for testing
    runs-on: ubuntu-latest
    needs: search_directories
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.search_directories.outputs.directories) }} 

    steps:
      - name: Display directory
        run: echo "Testing directory:" ${{ matrix.directory }}
