name: build and push Dockerfile

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Build and push
        run: |
          chmod +x ./push.sh
          ./push.sh
